name       : hal-flash
version    : 0.3.2
release    : 1
source     :
    - https://github.com/cshorler/hal-flash/archive/v0.3.2.tar.gz : cd176112b435c73a6b9b4e9078620b484f2db513d29f3a6e268c07bc10f10174
license    : GPL-2.0
summary    : Adobe Flash HAL shim library
description: |
    A shim library to expose HAL API to the Flash Player for DRM playback
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(gio-unix-2.0)
rundeps    :
    - udisks
libsplit   : no
setup      : |
    autoreconf -fi
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
