name       : hal-flash
version    : 0.3.3
release    : 2
source     :
    - https://github.com/cshorler/hal-flash/archive/v0.3.3.tar.gz : c69b96251acb8c6c9d4d293b77fdd3026eceabdb2e13ce7c03305790425f8937
license    : GPL-2.0
summary    : Adobe Flash HAL shim library
description: |
    A shim library to expose HAL API to the Flash Player for DRM playback
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(gio-unix-2.0)
rundeps    :
    - udisks
libsplit   : no
setup      : |
    autoreconf -fi
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
